version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "testedb"
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - mysql-compose-network
    restart: always

  adminer:
    image: adminer
    container_name: mysql_adminer
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - mysql-compose-network
    restart: always

networks: 
  mysql-compose-network:
    driver: bridge