version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
    restart: always
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "email"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network
    restart: always

networks: 
  postgres-compose-network:
    driver: bridge